name: Coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        env:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          NODE_ENV: 'production'
